spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 30
    refreshExpiration:
      minutes: 120
  oauth2:
    redirectUri: https://wishmagic-client-production.up.railway.app/oauth2/redirect
  cors:
    allowed-origins: https://wishmagic-client-production.up.railway.app/
