spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}