spring:
  application:
    name: movie-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: a8e45b01ab8660b4459d
            clientSecret: 6440ead072b77777a3659661d87b6f786a3d68a5
            scope: read:user, user:email
          google:
            clientId: 1081666627503-drnu19o033uti73mm8p8ormu733dr8g5.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  oauth2:
    redirectUri: https://wishmagic-client-production.up.railway.app/oauth2/redirect
  cors:
    allowed-origins: https://wishmagic-client-production.up.railway.app/

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
